baseurl = "/"
relativeURLs = true
languageCode = "en-us"
title = "Minimize Regret"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3
[[menu.main]]
    name = "Notes"
    url = "/note/"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"

[params]
    description = "Minimize Regret is a blog written by Tim Radtke about data science and machine learning."
    footer = "&copy; Tim Radtke 2017 | [Github](https://www.github.com/timradtke) | [Twitter](https://www.twitter.com/timradtke)"
